version: "3"
services:
  userdetail_postgressql:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
      POSTGRES_DB: UserDB
    healthcheck:
      test: PGPASSWORD=password  psql -U app -d UserDB -c "select 'Hello world'"
      interval: 1m30s
      timeout: 10s
      retries: 10

  userdetails:
    build: .
    image: userdetails:1
    depends_on:
      - userdetail_postgressql
    ports:
      - "8080:80"

